#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck disable=SC2034,SC2004

# Defaults
__DEVOXIO_DEFAULT_ETC_DIR="/etc/devoxio"
__DEVOXIO_DEFAULT_VAR_DIR="/var/lib/devoxio"
__DEVOXIO_USER_MODE=false
readonly __DEVOXIO_DEFAULT_CACHE_DIR="/tmp/.devoxio"
readonly __DEVOXIO_DEFAULT_LOG_FORMAT="[{TIMESTAMP}] {LEVEL}: {MESSAGE}"
readonly __DEVOXIO_DEFAULT_LOG_LEVEL=5 # Defaults to INFO
readonly __DEVOXIO_DEFAULT_LOG_TIMESTAMP="%T"

# Fallback to user directories if not running as root
if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    __DEVOXIO_DEFAULT_ETC_DIR="${XDG_CONFIG_HOME:-${HOME:-}/.config}/devoxio"
    __DEVOXIO_DEFAULT_VAR_DIR="${XDG_DATA_HOME:-${HOME:-}/.local/share}/devoxio"
    __DEVOXIO_USER_MODE=true
fi

# Exit codes
readonly __DEVOXIO_EXIT_OK=0  # Successful termination
readonly __DEVOXIO_EXIT_NOK=1 # Termination with errors

# Log levels
readonly __DEVOXIO_LOG_LEVEL_OFF=0
readonly __DEVOXIO_LOG_LEVEL_FATAL=1
readonly __DEVOXIO_LOG_LEVEL_ERROR=2
readonly __DEVOXIO_LOG_LEVEL_WARNING=3
readonly __DEVOXIO_LOG_LEVEL_NOTICE=4
readonly __DEVOXIO_LOG_LEVEL_INFO=5
readonly __DEVOXIO_LOG_LEVEL_DEBUG=6
readonly __DEVOXIO_LOG_LEVEL_TRACE=7
readonly __DEVOXIO_LOG_LEVEL_ALL=8

readonly -A __DEVOXIO_LOG_LEVELS=(
    [${__DEVOXIO_LOG_LEVEL_OFF}]="OFF"
    [${__DEVOXIO_LOG_LEVEL_FATAL}]="FATAL"
    [${__DEVOXIO_LOG_LEVEL_ERROR}]="ERROR"
    [${__DEVOXIO_LOG_LEVEL_WARNING}]="WARNING"
    [${__DEVOXIO_LOG_LEVEL_NOTICE}]="NOTICE"
    [${__DEVOXIO_LOG_LEVEL_INFO}]="INFO"
    [${__DEVOXIO_LOG_LEVEL_DEBUG}]="DEBUG"
    [${__DEVOXIO_LOG_LEVEL_TRACE}]="TRACE"
    [${__DEVOXIO_LOG_LEVEL_ALL}]="ALL"
)

# Colors
readonly __DEVOXIO_COLORS_ESCAPE="\033["
readonly __DEVOXIO_COLORS_RESET="${__DEVOXIO_COLORS_ESCAPE}0m"
readonly __DEVOXIO_COLORS_DEFAULT="${__DEVOXIO_COLORS_ESCAPE}39m"
readonly __DEVOXIO_COLORS_BLACK="${__DEVOXIO_COLORS_ESCAPE}30m"
readonly __DEVOXIO_COLORS_RED="${__DEVOXIO_COLORS_ESCAPE}31m"
readonly __DEVOXIO_COLORS_GREEN="${__DEVOXIO_COLORS_ESCAPE}32m"
readonly __DEVOXIO_COLORS_YELLOW="${__DEVOXIO_COLORS_ESCAPE}33m"
readonly __DEVOXIO_COLORS_BLUE="${__DEVOXIO_COLORS_ESCAPE}34m"
readonly __DEVOXIO_COLORS_MAGENTA="${__DEVOXIO_COLORS_ESCAPE}35m"
readonly __DEVOXIO_COLORS_CYAN="${__DEVOXIO_COLORS_ESCAPE}36m"
readonly __DEVOXIO_COLORS_LIGHT_GRAY="${__DEVOXIO_COLORS_ESCAPE}37m"
readonly __DEVOXIO_COLORS_BG_DEFAULT="${__DEVOXIO_COLORS_ESCAPE}49m"
readonly __DEVOXIO_COLORS_BG_BLACK="${__DEVOXIO_COLORS_ESCAPE}40m"
readonly __DEVOXIO_COLORS_BG_RED="${__DEVOXIO_COLORS_ESCAPE}41m"
readonly __DEVOXIO_COLORS_BG_GREEN="${__DEVOXIO_COLORS_ESCAPE}42m"
readonly __DEVOXIO_COLORS_BG_YELLOW="${__DEVOXIO_COLORS_ESCAPE}43m"
readonly __DEVOXIO_COLORS_BG_BLUE="${__DEVOXIO_COLORS_ESCAPE}44m"
readonly __DEVOXIO_COLORS_BG_MAGENTA="${__DEVOXIO_COLORS_ESCAPE}45m"
readonly __DEVOXIO_COLORS_BG_CYAN="${__DEVOXIO_COLORS_ESCAPE}46m"
readonly __DEVOXIO_COLORS_BG_WHITE="${__DEVOXIO_COLORS_ESCAPE}47m"