#!/usr/bin/env bash
# -*- coding: utf-8 -*-

set -o errexit  # Exit script when a command exits with non-zero status
set -o errtrace # Exit on error inside any functions or sub-shells
set -o nounset  # Exit script on use of an undefined variable
set -o pipefail # Return exit status of the last command in the pipe that failed

export __DEVOXIO_BIN
export __DEVOXIO_LIB_DIR

__DEVOXIO_BIN=$(readlink -f "${BASH_SOURCE[0]}")
__DEVOXIO_LIB_DIR=$(dirname "${__DEVOXIO_BIN}")

# Include devoxio library
source "${__DEVOXIO_LIB_DIR}/devoxio.sh"

# Execute source
# shellcheck source=/dev/null
source "$@"