#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck disable=SC2034,SC2004

# Defaults
readonly __XBASHIO_DEFAULT_CACHE_DIR="/tmp/.xbashio"
readonly __XBASHIO_DEFAULT_ETC_DIR="/etc/xbashio"
readonly __XBASHIO_DEFAULT_LOG_FORMAT="[{TIMESTAMP}] {LEVEL}: {MESSAGE}"
readonly __XBASHIO_DEFAULT_LOG_LEVEL=5 # Defaults to INFO
readonly __XBASHIO_DEFAULT_LOG_TIMESTAMP="%T"

# Exit codes
readonly __XBASHIO_EXIT_OK=0  # Successful termination
readonly __XBASHIO_EXIT_NOK=1 # Termination with errors

# Log levels
readonly __XBASHIO_LOG_LEVEL_OFF=0
readonly __XBASHIO_LOG_LEVEL_FATAL=1
readonly __XBASHIO_LOG_LEVEL_ERROR=2
readonly __XBASHIO_LOG_LEVEL_WARNING=3
readonly __XBASHIO_LOG_LEVEL_NOTICE=4
readonly __XBASHIO_LOG_LEVEL_INFO=5
readonly __XBASHIO_LOG_LEVEL_DEBUG=6
readonly __XBASHIO_LOG_LEVEL_TRACE=7
readonly __XBASHIO_LOG_LEVEL_ALL=8

readonly -A __XBASHIO_LOG_LEVELS=(
    [${__XBASHIO_LOG_LEVEL_OFF}]="OFF"
    [${__XBASHIO_LOG_LEVEL_FATAL}]="FATAL"
    [${__XBASHIO_LOG_LEVEL_ERROR}]="ERROR"
    [${__XBASHIO_LOG_LEVEL_WARNING}]="WARNING"
    [${__XBASHIO_LOG_LEVEL_NOTICE}]="NOTICE"
    [${__XBASHIO_LOG_LEVEL_INFO}]="INFO"
    [${__XBASHIO_LOG_LEVEL_DEBUG}]="DEBUG"
    [${__XBASHIO_LOG_LEVEL_TRACE}]="TRACE"
    [${__XBASHIO_LOG_LEVEL_ALL}]="ALL"
)

# Colors
readonly __XBASHIO_COLORS_ESCAPE="\033["
readonly __XBASHIO_COLORS_RESET="${__XBASHIO_COLORS_ESCAPE}0m"
readonly __XBASHIO_COLORS_DEFAULT="${__XBASHIO_COLORS_ESCAPE}39m"
readonly __XBASHIO_COLORS_BLACK="${__XBASHIO_COLORS_ESCAPE}30m"
readonly __XBASHIO_COLORS_RED="${__XBASHIO_COLORS_ESCAPE}31m"
readonly __XBASHIO_COLORS_GREEN="${__XBASHIO_COLORS_ESCAPE}32m"
readonly __XBASHIO_COLORS_YELLOW="${__XBASHIO_COLORS_ESCAPE}33m"
readonly __XBASHIO_COLORS_BLUE="${__XBASHIO_COLORS_ESCAPE}34m"
readonly __XBASHIO_COLORS_MAGENTA="${__XBASHIO_COLORS_ESCAPE}35m"
readonly __XBASHIO_COLORS_CYAN="${__XBASHIO_COLORS_ESCAPE}36m"
readonly __XBASHIO_COLORS_LIGHT_GRAY="${__XBASHIO_COLORS_ESCAPE}37m"
readonly __XBASHIO_COLORS_BG_DEFAULT="${__XBASHIO_COLORS_ESCAPE}49m"
readonly __XBASHIO_COLORS_BG_BLACK="${__XBASHIO_COLORS_ESCAPE}40m"
readonly __XBASHIO_COLORS_BG_RED="${__XBASHIO_COLORS_ESCAPE}41m"
readonly __XBASHIO_COLORS_BG_GREEN="${__XBASHIO_COLORS_ESCAPE}42m"
readonly __XBASHIO_COLORS_BG_YELLOW="${__XBASHIO_COLORS_ESCAPE}43m"
readonly __XBASHIO_COLORS_BG_BLUE="${__XBASHIO_COLORS_ESCAPE}44m"
readonly __XBASHIO_COLORS_BG_MAGENTA="${__XBASHIO_COLORS_ESCAPE}45m"
readonly __XBASHIO_COLORS_BG_CYAN="${__XBASHIO_COLORS_ESCAPE}46m"
readonly __XBASHIO_COLORS_BG_WHITE="${__XBASHIO_COLORS_ESCAPE}47m"
