#!/usr/bin/env bash
# -*- coding: utf-8 -*-

set -o errexit  # Exit script when a command exits with non-zero status
set -o errtrace # Exit on error inside any functions or sub-shells
set -o nounset  # Exit script on use of an undefined variable
set -o pipefail # Return exit status of the last command in the pipe that failed

export __XBASHIO_BIN
export __XBASHIO_LIB_DIR

__XBASHIO_BIN=$(readlink -f "${BASH_SOURCE[0]}")
__XBASHIO_LIB_DIR=$(dirname "${__XBASHIO_BIN}")

# Include xBashIO library
# shellcheck source=/workspaces/xbashio/src/xbashio/xbashio.sh
source "${__XBASHIO_LIB_DIR}/xbashio.sh"

# Execute source
# shellcheck source=/dev/null
source "$@"
